model: /path/MindSpeed-MM/configs/model/qwen2.5vl_3b.json

megatron_training:
  model: qwen2.5vl_3b
  use_fused_rmsnorm: true
  normalization: RMSNorm
  use_dynamic_bsz: true
  max_log_prob_seq_len_forward: 15000
  max_log_prob_seq_len_update: 5000
  use_mcore_models: true
  sequence_parallel: false
  use_flash_attn: true
  no_masked_softmax_fusion: true
  attention_softmax_in_fp32: true
  no_gradient_accumulation_fusion: true
  use_fused_swiglu: true
  swiglu: true
  bf16: true
  use_distributed_optimizer: true
  tokenizer_type: PretrainedFromHF
  tokenizer_name_or_path: /path/Qwen2.5-VL-3B-Instruct
  global_batch_size: 512
  seq_length: 1024
  save_interval: 50
  train_iters: 1000
  stage: ray_grpo
  attention_dropout: 0.0
  init_method_std: 0.01
  hidden_dropout: 0.0
  distributed_backend: nccl
  no_shared_storage: true
  variable_seq_lengths: true
  norm_epsilon: 1e-6
  dataset_additional_keys: ['input_ids', 'input_ids_length', 'attention_mask', 'position_ids']
  data_path: /path/dataset/rl_data
  split: 100,0,0
  use_deter_comp: false # 是否开启确定性计算

actor_config:
  model: qwen2.5vl_3b
  micro_batch_size: 2 # 需要被 global_batch_size * n_samples_per_prompt 整除
  tensor_model_parallel_size: 1
  pipeline_model_parallel_size: 1
  lr: 1e-6
  lr_decay_style: constant
  min_lr: 0.0
  weight_decay: 1.0e-2
  lr_warmup_fraction: 0.0
  clip_grad: 1.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  initial_loss_scale: 4096
  finetune: true
  load: /path/qwen2_5_vl_3b_tp1pp1
  save: ./ckpt
  no_load_optim: true
  no_load_rng: true
  num_workers: 8

rl_config:
  guarantee_order: true # TD 是否保序
  blocking: true
  gamma: 1.0
  lam: 0.95
  vit_forward_micro_batch_size: 64
  actor_forward_micro_batch_size: 64
  ref_forward_micro_batch_size: 64
  adv_estimator: group_norm
  kl_penalty: kl
  kl_ctrl_type: fixed
  init_kl_coef: 0.01
  mini_batch_size: 160
  max_prompt_length: 1024
  epochs: 1
  clip_ratio: 0.2
  entropy_coeff: 0.001
  shuffle_mini_batch: false
  n_samples_per_prompt: 5
  rule_reward: true
  num_cpus_for_local_task: 1.0
  num_cpus_for_placement_group: 8
  use_integrated_worker: true # 是否共卡
  reuse_image_embeds: true # 是否vit复用
  actor_resource:
    num_npus: 8

generate_config:
  # 多图场景最多图片数量
  limit_mm_image_per_prompt: 1
  limit_mm_video_per_prompt: 0

  # tokenizer相关配置
  micro_batch_size: 64 # Generation global_batch_size // data_parallel * n_samples整除
  trust_remote_code: true

  # 推理时的并行配置
  infer_tensor_parallel_size: 1
  infer_pipeline_parallel_size: 1
  infer_expert_parallel_size: 1

  # vllm 模型相关设置
  max_num_seqs: 64
  max_model_len: 3072 # prompt_length + response_length
  dtype: "bfloat16"
  gpu_memory_utilization: 0.8

  offload_train_optimizer: true
  offload_train_grad: true
  offload_train_param: true

  # 采样配置
  sampling_config:
    logprobs: 0
    max_tokens: 2048
    top_p: 1.
    top_k: -1
    min_p: 0.0
    temperature: 1.0
    detokenize: false
    seed: 1234
